# example netlify.toml
[build]
  command = "npm run docs:build"
  functions = "functions"
  publish = "dir"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
[[redirects]]
  force = true
  from = '/metrics/*'
  status = 200
  to = '/.netlify/functions/:splat'
[[redirects]]
  force = true
  from = '/api'
  status = 200
  to = '/.netlify/functions/index'
[[redirects]]
  force = true
  from = '/api/*'
  status = 200
  to = '/.netlify/functions/:splat'

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  [dev]
   command = "npm run docs:dev" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
